//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.12.18 at 12:10:35 PM GMT-10:00 
//


package org.hackystat.dailyprojectdata.resource.filemetric.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}FileData" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}Project use="required""/>
 *       &lt;attribute ref="{}Owner use="required""/>
 *       &lt;attribute ref="{}StartTime use="required""/>
 *       &lt;attribute ref="{}SizeMetric use="required""/>
 *       &lt;attribute ref="{}Tool use="required""/>
 *       &lt;attribute ref="{}UriPattern use="required""/>
 *       &lt;attribute ref="{}TotalSizeMetricValue use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fileData"
})
@XmlRootElement(name = "FileMetricDailyProjectData")
public class FileMetricDailyProjectData {

    @XmlElement(name = "FileData", required = true)
    protected List<FileData> fileData;
    @XmlAttribute(name = "Project", required = true)
    protected String project;
    @XmlAttribute(name = "Owner", required = true)
    protected String owner;
    @XmlAttribute(name = "StartTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTime;
    @XmlAttribute(name = "SizeMetric", required = true)
    protected String sizeMetric;
    @XmlAttribute(name = "Tool", required = true)
    protected String tool;
    @XmlAttribute(name = "UriPattern", required = true)
    protected String uriPattern;
    @XmlAttribute(name = "TotalSizeMetricValue", required = true)
    protected BigInteger totalSizeMetricValue;

    /**
     * Gets the value of the fileData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fileData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFileData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileData }
     * 
     * 
     */
    public List<FileData> getFileData() {
        if (fileData == null) {
            fileData = new ArrayList<FileData>();
        }
        return this.fileData;
    }

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProject() {
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProject(String value) {
        this.project = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the sizeMetric property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizeMetric() {
        return sizeMetric;
    }

    /**
     * Sets the value of the sizeMetric property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizeMetric(String value) {
        this.sizeMetric = value;
    }

    /**
     * Gets the value of the tool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTool() {
        return tool;
    }

    /**
     * Sets the value of the tool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTool(String value) {
        this.tool = value;
    }

    /**
     * Gets the value of the uriPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUriPattern() {
        return uriPattern;
    }

    /**
     * Sets the value of the uriPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUriPattern(String value) {
        this.uriPattern = value;
    }

    /**
     * Gets the value of the totalSizeMetricValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalSizeMetricValue() {
        return totalSizeMetricValue;
    }

    /**
     * Sets the value of the totalSizeMetricValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalSizeMetricValue(BigInteger value) {
        this.totalSizeMetricValue = value;
    }

}
