//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.28 at 12:01:58 PM GMT-10:00 
//


package org.hackystat.dailyprojectdata.resource.commit.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute ref="{}MemberUri"/>
 *       &lt;attribute ref="{}Commits"/>
 *       &lt;attribute ref="{}LinesAdded"/>
 *       &lt;attribute ref="{}LinesDeleted"/>
 *       &lt;attribute ref="{}LinesModified"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "MemberData")
public class MemberData
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlAttribute(name = "MemberUri")
    protected String memberUri;
    @XmlAttribute(name = "Commits")
    protected Integer commits;
    @XmlAttribute(name = "LinesAdded")
    protected Integer linesAdded;
    @XmlAttribute(name = "LinesDeleted")
    protected Integer linesDeleted;
    @XmlAttribute(name = "LinesModified")
    protected Integer linesModified;

    /**
     * Gets the value of the memberUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberUri() {
        return memberUri;
    }

    /**
     * Sets the value of the memberUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberUri(String value) {
        this.memberUri = value;
    }

    public boolean isSetMemberUri() {
        return (this.memberUri!= null);
    }

    /**
     * Gets the value of the commits property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getCommits() {
        return commits;
    }

    /**
     * Sets the value of the commits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCommits(int value) {
        this.commits = value;
    }

    public boolean isSetCommits() {
        return (this.commits!= null);
    }

    public void unsetCommits() {
        this.commits = null;
    }

    /**
     * Gets the value of the linesAdded property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getLinesAdded() {
        return linesAdded;
    }

    /**
     * Sets the value of the linesAdded property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLinesAdded(int value) {
        this.linesAdded = value;
    }

    public boolean isSetLinesAdded() {
        return (this.linesAdded!= null);
    }

    public void unsetLinesAdded() {
        this.linesAdded = null;
    }

    /**
     * Gets the value of the linesDeleted property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getLinesDeleted() {
        return linesDeleted;
    }

    /**
     * Sets the value of the linesDeleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLinesDeleted(int value) {
        this.linesDeleted = value;
    }

    public boolean isSetLinesDeleted() {
        return (this.linesDeleted!= null);
    }

    public void unsetLinesDeleted() {
        this.linesDeleted = null;
    }

    /**
     * Gets the value of the linesModified property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getLinesModified() {
        return linesModified;
    }

    /**
     * Sets the value of the linesModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLinesModified(int value) {
        this.linesModified = value;
    }

    public boolean isSetLinesModified() {
        return (this.linesModified!= null);
    }

    public void unsetLinesModified() {
        this.linesModified = null;
    }

}
